# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Test

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
    
- task: accuknox-secret-scan@1
  inputs:
    accuknoxEndpoint: '$(accuknox-enpoint)'
    accuknoxToken: '$(accuknox-token)'
    accuknoxLabel: '$(accuknox-label)'
    inputSoftFail: false